### ISSUE TITLE
Loss of precision when writing geometry with more than 6 decimal places to string

### ISSUE THREAD

**Issue by prusswan** [cleder/fastkml#67] opened 2018-04-18 07:27 UTC
e.g. `(103.7940492, 1.4391202)` -> `103.794049,1.439120`

In `geometry.py`,  `_etree_coordinates(self, coordinates)` is casting coordinates to `%f`, reducing the values to 6 decimal places.

**Comment by AranVinkItility** [comment] 2019-08-05 12:51
+1 for this, could not find out why my points where not at the intended point on the map.

**Comment by MShields1986** [comment] 2022-10-28 17:26
+1

**Comment by cleder** [comment] 2023-01-16 02:34
PR #98

**Comment by cleder** [comment] 2023-10-30 22:13
Duplicate of #217

**Comment by cleder** [comment] 2023-11-02 09:35
Closing this in favour of #217

**Closed** 2024-02-06 18:56 UTC
